name: Run Unit Tests on Pull Request

on: 
  pull_request:
env:
  BIGQUERY_PROJECT: ${{ secrets.BIGQUERY_PROJECT }}
  KEYFILE_LOCATION: ./dbt-service-account.json

jobs:
  pytest_run_all:
    name: Pytest Run All
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
        working-directory: ./unit_tests
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Authenticate using service account
        run: 'echo "$KEYFILE" > ./dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.GCP_BIGQUERY_USER_KEYFILE}}

      - name: Install dependencies
        run: |
          pip install dbt-core
          pip install dbt-bigquery
          pip install pytest
      
      - name: Run tests
        run: python -m pytest .